### ISSUE TITLE
systemd-nspawn --suppress-sync=yes

### ISSUE THREAD

**Issue by kapouer** [Truelite/nspawn-runner#11]
For the record, another optimization that might make sense.
I'll time it if that is actually faster... surely it isn't when volatile=overlay.

**Comment by spanezz** [comment]
Uh, yes, and TIL! For non-tmpfs cases it looks like it makes a lot of sense

**Comment by spanezz** [comment]
`--suppress-sync=yes` is available since systemd 250, which is available from `bullseye-backports`.

I'll add it by default, conditional on the installed version of systemd
